<?php

namespace App\Livewire\Storefront\Admin;

use App\Models\InventoryCategory;
use App\Models\InventoryItem;
use App\Models\InventoryItemMedia;
use App\Models\StorefrontCoupon;
use App\Models\StorefrontCouponUsage;
use App\Models\StorefrontProductCombo;
use App\Support\BranchContext;
use App\Support\StorefrontMedia;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

#[Layout('layouts.app.sidebar')]
#[Title('Storefront Products')]
class ProductManager extends Component
{
    use WithFileUploads;
    use WithPagination;

    public string $tab = 'products';

    #[Url(as: 'products_q')]
    public string $productSearch = '';

    #[Url(as: 'combos_q')]
    public string $comboSearch = '';

    #[Url(as: 'coupons_q')]
    public string $couponSearch = '';

    public int $perPage = 10;
    public bool $showComboModal = false;
    public bool $showCouponModal = false;

    public ?int $editingProductId = null;
    public string $productName = '';
    public string $productShortDescription = '';
    public string $productDescription = '';
    public string $productSku = '';
    public string $productStatus = 'draft';
    public ?int $productCategoryId = null;
    public ?float $productPrice = null;
    public ?float $productCompareAtPrice = null;
    public bool $productTrackStock = true;
    public ?float $productStockQuantity = 0;
    public ?float $productLowStockThreshold = 0;
    public bool $productAllowBackorders = false;
    public bool $productVisible = true;
    public bool $productFeatured = false;
    public bool $productTaxable = false;
    public ?float $productWeight = null;
    public ?float $productLength = null;
    public ?float $productWidth = null;
    public ?float $productHeight = null;
    public string $productSizes = '';
    public string $productColors = '';
    public $productFeaturedImageUpload = null;
    public ?string $productFeaturedImagePath = null;
    public array $productGalleryUploads = [];
    public array $existingProductGallery = [];

    public ?int $editingComboId = null;
    public string $comboName = '';
    public string $comboDescription = '';
    public ?float $comboPrice = 0;
    public array $comboProductIds = [];
    public bool $comboActive = true;
    public bool $comboVisible = true;
    public int $comboSortOrder = 0;
    public $comboFeaturedImageUpload = null;
    public ?string $comboFeaturedImagePath = null;

    public ?int $editingCouponId = null;
    public string $couponName = '';
    public string $couponCode = '';
    public string $couponDescription = '';
    public string $couponDiscountType = 'fixed';
    public ?float $couponDiscountValue = 0;
    public ?float $couponMinSubtotal = null;
    public ?float $couponMaxDiscountAmount = null;
    public ?string $couponStartsAt = null;
    public ?string $couponEndsAt = null;
    public ?int $couponUsageLimit = null;
    public ?int $couponPerCustomerLimit = null;
    public bool $couponActive = true;
    public bool $couponAutoGenerated = false;

    public function mount(): void
    {
        abort_unless(auth()->user()?->can('storefront.catalog.manage'), 403);
    }

    public function updatedProductSearch(): void
    {
        $this->resetPage('productsPage');
    }

    public function updatedComboSearch(): void
    {
        $this->resetPage('combosPage');
    }

    public function updatedCouponSearch(): void
    {
        $this->resetPage('couponsPage');
    }

    public function saveProduct(): void
    {
        $this->authorize('storefront.catalog.manage');

        $validated = $this->validate([
            'productName' => ['required', 'string', 'max:191'],
            'productShortDescription' => ['nullable', 'string', 'max:2000'],
            'productDescription' => ['nullable', 'string', 'max:20000'],
            'productSku' => [
                'nullable',
                'string',
                'max:100',
                Rule::unique('inventory_items', 'sku')->ignore($this->editingProductId),
            ],
            'productStatus' => ['required', Rule::in(['draft', 'active', 'inactive'])],
            'productCategoryId' => ['nullable', 'integer', 'exists:inventory_categories,id'],
            'productPrice' => ['required', 'numeric', 'min:0'],
            'productCompareAtPrice' => ['nullable', 'numeric', 'min:0'],
            'productTrackStock' => ['boolean'],
            'productStockQuantity' => ['nullable', 'numeric', 'min:0'],
            'productLowStockThreshold' => ['nullable', 'numeric', 'min:0'],
            'productAllowBackorders' => ['boolean'],
            'productVisible' => ['boolean'],
            'productFeatured' => ['boolean'],
            'productTaxable' => ['boolean'],
            'productWeight' => ['nullable', 'numeric', 'min:0'],
            'productLength' => ['nullable', 'numeric', 'min:0'],
            'productWidth' => ['nullable', 'numeric', 'min:0'],
            'productHeight' => ['nullable', 'numeric', 'min:0'],
            'productSizes' => ['nullable', 'string', 'max:2000'],
            'productColors' => ['nullable', 'string', 'max:2000'],
            'productFeaturedImageUpload' => [
                'nullable',
                'image',
                'mimes:jpg,jpeg,png,webp',
                'mimetypes:image/jpeg,image/png,image/webp',
                'max:4096',
                'dimensions:min_width=64,min_height=64,max_width=4096,max_height=4096',
            ],
            'productGalleryUploads' => ['nullable', 'array', 'max:12'],
            'productGalleryUploads.*' => [
                'nullable',
                'image',
                'mimes:jpg,jpeg,png,webp',
                'mimetypes:image/jpeg,image/png,image/webp',
                'max:4096',
                'dimensions:min_width=64,min_height=64,max_width=4096,max_height=4096',
            ],
        ]);

        $branchId = $this->resolveBranchId();
        $name = $this->sanitizeText($validated['productName']) ?? 'Product';
        $status = strtolower($validated['productStatus']);
        $isActive = $status === 'active';

        $payload = [
            'branch_id' => $branchId,
            'inventory_category_id' => $validated['productCategoryId'] ?: null,
            'inventory_unit_id' => null,
            'sku' => $this->prepareSku($validated['productSku'] ?? null),
            'name' => $name,
            'slug' => $this->generateUniqueProductSlug($name, $branchId, $this->editingProductId),
            'unit' => 'pcs',
            'short_description' => $this->sanitizeText($validated['productShortDescription'] ?? null),
            'full_description' => $this->sanitizeText($validated['productDescription'] ?? null),
            'status' => $status,
            'default_buy_price' => null,
            'default_sell_price' => round((float) $validated['productPrice'], 2),
            'compare_at_price' => $validated['productCompareAtPrice'] !== null
                ? round((float) $validated['productCompareAtPrice'], 2)
                : null,
            'track_stock' => (bool) $validated['productTrackStock'],
            'reorder_level' => round((float) ($validated['productLowStockThreshold'] ?? 0), 2),
            'low_stock_threshold' => round((float) ($validated['productLowStockThreshold'] ?? 0), 2),
            'allow_backorders' => (bool) $validated['productAllowBackorders'],
            'storefront_is_visible' => (bool) $validated['productVisible'] && $isActive,
            'is_featured' => (bool) $validated['productFeatured'],
            'weight' => $validated['productWeight'],
            'dimensions' => $this->dimensionsPayload(
                $validated['productLength'] ?? null,
                $validated['productWidth'] ?? null,
                $validated['productHeight'] ?? null
            ),
            'shipping_profile_id' => null,
            'is_taxable' => (bool) $validated['productTaxable'],
            'meta_title' => $name,
            'meta_description' => $this->sanitizeText($validated['productShortDescription'] ?? null),
            'is_active' => $isActive,
        ];

        $product = $this->editingProductId
            ? InventoryItem::query()->with(['media', 'stock'])->findOrFail($this->editingProductId)
            : new InventoryItem();

        if ($this->productFeaturedImageUpload) {
            if ($product->exists && $product->featured_image_path) {
                StorefrontMedia::delete($product->featured_image_path);
            }

            $payload['featured_image_path'] = StorefrontMedia::store($this->productFeaturedImageUpload, 'storefront/products/featured');
        }

        $product->fill($payload);
        $product->save();

        $product->stock()->updateOrCreate(
            ['inventory_item_id' => $product->id],
            [
                'branch_id' => $product->branch_id,
                'qty_on_hand' => round((float) ($validated['productStockQuantity'] ?? 0), 2),
                'qty_reserved' => (float) ($product->stock?->qty_reserved ?? 0),
            ]
        );

        $this->syncProductVariants(
            $product,
            $this->splitCsv($validated['productSizes'] ?? ''),
            $this->splitCsv($validated['productColors'] ?? '')
        );

        $this->appendGalleryUploads($product);

        session()->flash('success', $this->editingProductId ? 'Product updated.' : 'Product created.');
        $this->resetProductForm();
    }

    public function editProduct(int $productId): void
    {
        $this->authorize('storefront.catalog.manage');

        $product = InventoryItem::query()
            ->with(['media', 'variants', 'stock'])
            ->findOrFail($productId);

        $this->editingProductId = $product->id;
        $this->productName = $product->name;
        $this->productShortDescription = (string) ($product->short_description ?? '');
        $this->productDescription = (string) ($product->full_description ?? '');
        $this->productSku = (string) ($product->sku ?? '');
        $this->productStatus = (string) ($product->status ?: 'draft');
        $this->productCategoryId = $product->inventory_category_id;
        $this->productPrice = $product->default_sell_price !== null ? (float) $product->default_sell_price : null;
        $this->productCompareAtPrice = $product->compare_at_price !== null ? (float) $product->compare_at_price : null;
        $this->productTrackStock = (bool) $product->track_stock;
        $this->productStockQuantity = $product->stock ? (float) $product->stock->qty_on_hand : 0;
        $this->productLowStockThreshold = $product->low_stock_threshold !== null
            ? (float) $product->low_stock_threshold
            : 0;
        $this->productAllowBackorders = (bool) $product->allow_backorders;
        $this->productVisible = (bool) $product->storefront_is_visible;
        $this->productFeatured = (bool) $product->is_featured;
        $this->productTaxable = (bool) $product->is_taxable;
        $this->productWeight = $product->weight !== null ? (float) $product->weight : null;
        $this->productLength = data_get($product->dimensions, 'length');
        $this->productWidth = data_get($product->dimensions, 'width');
        $this->productHeight = data_get($product->dimensions, 'height');
        $this->productSizes = $product->variants->pluck('size')->filter()->unique()->implode(', ');
        $this->productColors = $product->variants->pluck('color')->filter()->unique()->implode(', ');
        $this->existingProductGallery = $product->media->map(fn (InventoryItemMedia $media) => [
            'id' => $media->id,
            'path' => $media->path,
            'image_url' => $media->image_url,
            'alt_text' => $media->alt_text,
        ])->all();
        $this->productFeaturedImagePath = $product->featured_image_path;

        $this->productFeaturedImageUpload = null;
        $this->productGalleryUploads = [];
        $this->tab = 'products';
    }

    public function removeProductMedia(int $mediaId): void
    {
        $this->authorize('storefront.catalog.manage');

        $media = InventoryItemMedia::query()->findOrFail($mediaId);
        $product = InventoryItem::query()->findOrFail($media->inventory_item_id);

        StorefrontMedia::delete($media->path);
        $media->delete();

        $this->syncGalleryImagesColumn($product->fresh('media'));

        $this->existingProductGallery = collect($this->existingProductGallery)
            ->reject(fn (array $image) => (int) $image['id'] === $mediaId)
            ->values()
            ->all();

        session()->flash('success', 'Product image removed.');
    }

    public function deleteProduct(int $productId): void
    {
        $this->authorize('storefront.catalog.manage');

        $product = InventoryItem::query()->with(['media'])->findOrFail($productId);

        $isUsedInOrders = \App\Models\OrderLine::query()->where('inventory_item_id', $product->id)->exists();
        if ($isUsedInOrders) {
            throw ValidationException::withMessages([
                'productName' => 'This product is already used in orders and cannot be deleted.',
            ]);
        }

        if ($product->featured_image_path) {
            StorefrontMedia::delete($product->featured_image_path);
        }

        foreach ($product->media as $media) {
            StorefrontMedia::delete($media->path);
        }

        $product->delete();

        if ($this->editingProductId === $productId) {
            $this->resetProductForm();
        }

        session()->flash('success', 'Product deleted.');
    }

    public function resetProductForm(): void
    {
        $this->editingProductId = null;
        $this->productName = '';
        $this->productShortDescription = '';
        $this->productDescription = '';
        $this->productSku = '';
        $this->productStatus = 'draft';
        $this->productCategoryId = null;
        $this->productPrice = null;
        $this->productCompareAtPrice = null;
        $this->productTrackStock = true;
        $this->productStockQuantity = 0;
        $this->productLowStockThreshold = 0;
        $this->productAllowBackorders = false;
        $this->productVisible = true;
        $this->productFeatured = false;
        $this->productTaxable = false;
        $this->productWeight = null;
        $this->productLength = null;
        $this->productWidth = null;
        $this->productHeight = null;
        $this->productSizes = '';
        $this->productColors = '';
        $this->productFeaturedImageUpload = null;
        $this->productFeaturedImagePath = null;
        $this->productGalleryUploads = [];
        $this->existingProductGallery = [];
        $this->resetErrorBag();
    }

    public function saveCombo(): void
    {
        $this->authorize('storefront.catalog.manage');

        $validated = $this->validate([
            'comboName' => ['required', 'string', 'max:191'],
            'comboDescription' => ['nullable', 'string', 'max:4000'],
            'comboPrice' => ['required', 'numeric', 'min:0'],
            'comboProductIds' => ['required', 'array', 'min:1'],
            'comboProductIds.*' => ['integer', 'exists:inventory_items,id'],
            'comboActive' => ['boolean'],
            'comboVisible' => ['boolean'],
            'comboSortOrder' => ['nullable', 'integer', 'min:0', 'max:9999'],
            'comboFeaturedImageUpload' => [
                'nullable',
                'image',
                'mimes:jpg,jpeg,png,webp',
                'mimetypes:image/jpeg,image/png,image/webp',
                'max:4096',
                'dimensions:min_width=64,min_height=64,max_width=4096,max_height=4096',
            ],
        ]);

        $branchId = $this->resolveBranchId();
        $name = $this->sanitizeText($validated['comboName']) ?? 'Combo';

        $combo = $this->editingComboId
            ? StorefrontProductCombo::query()->findOrFail($this->editingComboId)
            : new StorefrontProductCombo();

        $payload = [
            'branch_id' => $branchId,
            'name' => $name,
            'slug' => $this->generateUniqueComboSlug($name, $branchId, $this->editingComboId),
            'description' => $this->sanitizeText($validated['comboDescription'] ?? null),
            'price' => round((float) $validated['comboPrice'], 2),
            'is_active' => (bool) $validated['comboActive'],
            'storefront_is_visible' => (bool) $validated['comboVisible'],
            'sort_order' => (int) ($validated['comboSortOrder'] ?? 0),
        ];

        if ($this->comboFeaturedImageUpload) {
            if ($combo->exists && $combo->featured_image_path) {
                StorefrontMedia::delete($combo->featured_image_path);
            }

            $payload['featured_image_path'] = StorefrontMedia::store($this->comboFeaturedImageUpload, 'storefront/combos');
        }

        $combo->fill($payload);
        $combo->save();

        $syncPayload = [];
        foreach ($validated['comboProductIds'] as $productId) {
            $syncPayload[(int) $productId] = ['quantity' => 1];
        }
        $combo->products()->sync($syncPayload);

        session()->flash('success', $this->editingComboId ? 'Combo updated.' : 'Combo created.');
        $this->resetComboForm();
        $this->showComboModal = false;
    }

    public function editCombo(int $comboId): void
    {
        $this->authorize('storefront.catalog.manage');

        $combo = StorefrontProductCombo::query()->with('products')->findOrFail($comboId);

        $this->editingComboId = $combo->id;
        $this->comboName = $combo->name;
        $this->comboDescription = (string) ($combo->description ?? '');
        $this->comboPrice = $combo->price !== null ? (float) $combo->price : 0;
        $this->comboProductIds = $combo->products->pluck('id')->map(fn ($id) => (int) $id)->all();
        $this->comboActive = (bool) $combo->is_active;
        $this->comboVisible = (bool) $combo->storefront_is_visible;
        $this->comboSortOrder = (int) ($combo->sort_order ?? 0);
        $this->comboFeaturedImagePath = $combo->featured_image_path;
        $this->comboFeaturedImageUpload = null;
        $this->showComboModal = true;
    }

    public function deleteCombo(int $comboId): void
    {
        $this->authorize('storefront.catalog.manage');

        $combo = StorefrontProductCombo::query()->findOrFail($comboId);

        if ($combo->featured_image_path) {
            StorefrontMedia::delete($combo->featured_image_path);
        }

        $combo->delete();

        if ($this->editingComboId === $comboId) {
            $this->resetComboForm();
        }

        session()->flash('success', 'Combo deleted.');
    }

    public function resetComboForm(): void
    {
        $this->editingComboId = null;
        $this->comboName = '';
        $this->comboDescription = '';
        $this->comboPrice = 0;
        $this->comboProductIds = [];
        $this->comboActive = true;
        $this->comboVisible = true;
        $this->comboSortOrder = 0;
        $this->comboFeaturedImageUpload = null;
        $this->comboFeaturedImagePath = null;
        $this->resetErrorBag();
    }

    public function openCreateComboModal(): void
    {
        $this->authorize('storefront.catalog.manage');
        $this->resetComboForm();
        $this->showComboModal = true;
    }

    public function closeComboModal(): void
    {
        $this->showComboModal = false;
        $this->resetComboForm();
    }

    public function generateCouponCode(): void
    {
        $prefix = Str::upper(Str::substr(Str::slug($this->couponName, ''), 0, 4));
        if ($prefix === '') {
            $prefix = 'TP';
        }

        $this->couponCode = $prefix.'-'.Str::upper(Str::random(6));
        $this->couponAutoGenerated = true;
    }

    public function saveCoupon(): void
    {
        $this->authorize('storefront.catalog.manage');

        $branchId = $this->resolveBranchId();
        $normalizedCode = $this->normalizeCouponCode($this->couponCode);

        $codeRule = Rule::unique('storefront_coupons', 'code')
            ->where(fn ($query) => $query->where('branch_id', $branchId));

        if ($this->editingCouponId) {
            $codeRule = $codeRule->ignore($this->editingCouponId);
        }

        $validated = $this->validate([
            'couponName' => ['required', 'string', 'max:191'],
            'couponDescription' => ['nullable', 'string', 'max:4000'],
            'couponDiscountType' => ['required', Rule::in(['fixed', 'percent'])],
            'couponDiscountValue' => [
                'required',
                'numeric',
                'min:0',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    if ($this->couponDiscountType === 'percent' && (float) $value > 100) {
                        $fail('Percentage discount cannot exceed 100.');
                    }
                },
            ],
            'couponMinSubtotal' => ['nullable', 'numeric', 'min:0'],
            'couponMaxDiscountAmount' => ['nullable', 'numeric', 'min:0'],
            'couponStartsAt' => ['nullable', 'date'],
            'couponEndsAt' => ['nullable', 'date', 'after_or_equal:couponStartsAt'],
            'couponUsageLimit' => ['nullable', 'integer', 'min:1'],
            'couponPerCustomerLimit' => ['nullable', 'integer', 'min:1'],
            'couponActive' => ['boolean'],
        ]);

        validator(
            ['couponCode' => $normalizedCode],
            ['couponCode' => ['required', 'string', 'max:80', 'regex:/^[A-Z0-9_-]+$/', $codeRule]]
        )->validate();

        $payload = [
            'branch_id' => $branchId,
            'name' => $this->sanitizeText($validated['couponName']) ?? 'Coupon',
            'code' => $normalizedCode,
            'description' => $this->sanitizeText($validated['couponDescription'] ?? null),
            'discount_type' => $validated['couponDiscountType'],
            'discount_value' => round((float) $validated['couponDiscountValue'], 2),
            'min_subtotal' => $validated['couponMinSubtotal'],
            'max_discount_amount' => $validated['couponMaxDiscountAmount'],
            'starts_at' => $validated['couponStartsAt'] ?: null,
            'ends_at' => $validated['couponEndsAt'] ?: null,
            'usage_limit' => $validated['couponUsageLimit'],
            'per_customer_limit' => $validated['couponPerCustomerLimit'],
            'is_active' => (bool) $validated['couponActive'],
            'is_auto_generated' => $this->couponAutoGenerated,
        ];

        if ($this->editingCouponId) {
            StorefrontCoupon::query()->findOrFail($this->editingCouponId)->update($payload);
            session()->flash('success', 'Coupon updated.');
        } else {
            $payload['used_count'] = 0;
            StorefrontCoupon::query()->create($payload);
            session()->flash('success', 'Coupon created.');
        }

        $this->resetCouponForm();
        $this->showCouponModal = false;
    }

    public function editCoupon(int $couponId): void
    {
        $this->authorize('storefront.catalog.manage');

        $coupon = StorefrontCoupon::query()->findOrFail($couponId);

        $this->editingCouponId = $coupon->id;
        $this->couponName = $coupon->name;
        $this->couponCode = $coupon->code;
        $this->couponDescription = (string) ($coupon->description ?? '');
        $this->couponDiscountType = $coupon->discount_type;
        $this->couponDiscountValue = $coupon->discount_value !== null ? (float) $coupon->discount_value : 0;
        $this->couponMinSubtotal = $coupon->min_subtotal !== null ? (float) $coupon->min_subtotal : null;
        $this->couponMaxDiscountAmount = $coupon->max_discount_amount !== null ? (float) $coupon->max_discount_amount : null;
        $this->couponStartsAt = $coupon->starts_at?->format('Y-m-d\TH:i');
        $this->couponEndsAt = $coupon->ends_at?->format('Y-m-d\TH:i');
        $this->couponUsageLimit = $coupon->usage_limit;
        $this->couponPerCustomerLimit = $coupon->per_customer_limit;
        $this->couponActive = (bool) $coupon->is_active;
        $this->couponAutoGenerated = (bool) $coupon->is_auto_generated;
        $this->showCouponModal = true;
    }

    public function deleteCoupon(int $couponId): void
    {
        $this->authorize('storefront.catalog.manage');

        $coupon = StorefrontCoupon::query()->findOrFail($couponId);
        $hasUsages = StorefrontCouponUsage::query()->where('storefront_coupon_id', $coupon->id)->exists();

        if ($hasUsages) {
            $coupon->update(['is_active' => false]);
            session()->flash('success', 'Coupon has existing usage records and was disabled instead of deleted.');

            return;
        }

        $coupon->delete();

        if ($this->editingCouponId === $couponId) {
            $this->resetCouponForm();
        }

        session()->flash('success', 'Coupon deleted.');
    }

    public function resetCouponForm(): void
    {
        $this->editingCouponId = null;
        $this->couponName = '';
        $this->couponCode = '';
        $this->couponDescription = '';
        $this->couponDiscountType = 'fixed';
        $this->couponDiscountValue = 0;
        $this->couponMinSubtotal = null;
        $this->couponMaxDiscountAmount = null;
        $this->couponStartsAt = null;
        $this->couponEndsAt = null;
        $this->couponUsageLimit = null;
        $this->couponPerCustomerLimit = null;
        $this->couponActive = true;
        $this->couponAutoGenerated = false;
        $this->resetErrorBag();
    }

    public function openCreateCouponModal(): void
    {
        $this->authorize('storefront.catalog.manage');
        $this->resetCouponForm();
        $this->showCouponModal = true;
    }

    public function closeCouponModal(): void
    {
        $this->showCouponModal = false;
        $this->resetCouponForm();
    }

    protected function syncProductVariants(InventoryItem $product, array $sizes, array $colors): void
    {
        $variants = [];
        $index = 1;

        if ($sizes !== [] && $colors !== []) {
            foreach ($sizes as $size) {
                foreach ($colors as $color) {
                    $variants[] = $this->variantPayload($product, $size, $color, $index++);
                }
            }
        } elseif ($sizes !== []) {
            foreach ($sizes as $size) {
                $variants[] = $this->variantPayload($product, $size, null, $index++);
            }
        } elseif ($colors !== []) {
            foreach ($colors as $color) {
                $variants[] = $this->variantPayload($product, null, $color, $index++);
            }
        }

        $product->variants()->delete();

        if ($variants !== []) {
            $product->variants()->createMany($variants);
        }
    }

    protected function variantPayload(InventoryItem $product, ?string $size, ?string $color, int $index): array
    {
        $sizeLabel = $size ? strtoupper($size) : null;
        $colorLabel = $this->normalizeColorValue($color);

        $name = trim(implode(' / ', array_filter([$sizeLabel, $colorLabel])));
        if ($name === '') {
            $name = 'Variant '.$index;
        }

        return [
            'name' => $name,
            'size' => $sizeLabel,
            'color' => $colorLabel,
            'sku' => $product->sku.'-V'.str_pad((string) $index, 2, '0', STR_PAD_LEFT),
            'price_delta' => 0,
            'stock_qty' => null,
            'option_values' => [
                'size' => $sizeLabel,
                'color' => $colorLabel,
            ],
            'is_active' => true,
        ];
    }

    protected function normalizeColorValue(?string $value): ?string
    {
        $candidate = trim(strip_tags((string) $value));
        if ($candidate === '') {
            return null;
        }

        if (preg_match('/^#([0-9a-fA-F]{3})$/', $candidate, $matches)) {
            $hex = strtoupper($matches[1]);

            return '#'.$hex[0].$hex[0].$hex[1].$hex[1].$hex[2].$hex[2];
        }

        if (preg_match('/^#([0-9a-fA-F]{6})$/', $candidate)) {
            return '#'.strtoupper(substr($candidate, 1));
        }

        return Str::title(Str::lower($candidate));
    }

    protected function appendGalleryUploads(InventoryItem $product): void
    {
        $uploads = array_filter($this->productGalleryUploads);
        if ($uploads === []) {
            $this->syncGalleryImagesColumn($product->fresh('media'));

            return;
        }

        $maxSort = (int) ($product->media()->max('sort_order') ?? 0);
        foreach ($uploads as $upload) {
            $path = StorefrontMedia::store($upload, 'storefront/products/gallery');
            $maxSort++;

            $product->media()->create([
                'path' => $path,
                'alt_text' => $product->name,
                'sort_order' => $maxSort,
            ]);
        }

        $this->syncGalleryImagesColumn($product->fresh('media'));
        $this->productGalleryUploads = [];
    }

    protected function syncGalleryImagesColumn(InventoryItem $product): void
    {
        $paths = $product->media->pluck('path')->values()->all();
        $product->update([
            'gallery_images' => $paths,
        ]);
    }

    protected function resolveBranchId(): int
    {
        $user = auth()->user();
        if (! $user) {
            throw ValidationException::withMessages([
                'tab' => 'Authenticated user is required.',
            ]);
        }

        if (! $user->isGlobalAdmin()) {
            if (! $user->branch_id) {
                throw ValidationException::withMessages([
                    'tab' => 'Your account is not assigned to a branch.',
                ]);
            }

            return (int) $user->branch_id;
        }

        $branchId = BranchContext::id() ?: $user->branch_id;
        if (! $branchId) {
            throw ValidationException::withMessages([
                'tab' => 'Select a branch from the branch switcher before creating storefront records.',
            ]);
        }

        return (int) $branchId;
    }

    protected function generateUniqueProductSlug(string $name, int $branchId, ?int $ignoreId = null): string
    {
        $baseSlug = Str::slug($name);
        if ($baseSlug === '') {
            $baseSlug = 'product';
        }

        $candidate = $baseSlug;
        $suffix = 2;

        while (InventoryItem::query()
            ->withoutBranchScope()
            ->where('branch_id', $branchId)
            ->where('slug', $candidate)
            ->when($ignoreId !== null, fn ($query) => $query->where('id', '!=', $ignoreId))
            ->exists()) {
            $candidate = $baseSlug.'-'.$suffix;
            $suffix++;
        }

        return $candidate;
    }

    protected function generateUniqueComboSlug(string $name, int $branchId, ?int $ignoreId = null): string
    {
        $baseSlug = Str::slug($name);
        if ($baseSlug === '') {
            $baseSlug = 'combo';
        }

        $candidate = $baseSlug;
        $suffix = 2;

        while (StorefrontProductCombo::query()
            ->withoutBranchScope()
            ->where('branch_id', $branchId)
            ->where('slug', $candidate)
            ->when($ignoreId !== null, fn ($query) => $query->where('id', '!=', $ignoreId))
            ->exists()) {
            $candidate = $baseSlug.'-'.$suffix;
            $suffix++;
        }

        return $candidate;
    }

    protected function prepareSku(?string $provided): string
    {
        $candidate = strtoupper(trim((string) $provided));
        if ($candidate !== '') {
            return $candidate;
        }

        do {
            $candidate = 'PRD-'.Str::upper(Str::random(8));
        } while (InventoryItem::query()->withoutBranchScope()->where('sku', $candidate)->exists());

        return $candidate;
    }

    protected function dimensionsPayload(?float $length, ?float $width, ?float $height): ?array
    {
        $payload = array_filter([
            'length' => $length,
            'width' => $width,
            'height' => $height,
        ], fn ($value) => $value !== null && $value !== '');

        return $payload === [] ? null : $payload;
    }

    /**
     * @return array<int, string>
     */
    protected function splitCsv(string $value): array
    {
        return collect(explode(',', $value))
            ->map(fn ($item) => trim(strip_tags($item)))
            ->filter()
            ->unique()
            ->values()
            ->all();
    }

    protected function sanitizeText(?string $value): ?string
    {
        if ($value === null) {
            return null;
        }

        $sanitized = trim(strip_tags($value));

        return $sanitized === '' ? null : $sanitized;
    }

    protected function normalizeCouponCode(string $code): string
    {
        $normalized = strtoupper(trim(strip_tags($code)));
        $normalized = preg_replace('/\s+/', '', $normalized) ?: '';

        return $normalized;
    }

    public function render()
    {
        $products = InventoryItem::query()
            ->with(['category', 'stock', 'media'])
            ->when($this->productSearch !== '', function ($query) {
                $query->where(function ($inner) {
                    $term = '%'.$this->productSearch.'%';
                    $inner->where('name', 'like', $term)
                        ->orWhere('sku', 'like', $term)
                        ->orWhere('slug', 'like', $term);
                });
            })
            ->orderByDesc('id')
            ->paginate($this->perPage, ['*'], 'productsPage');

        $combos = StorefrontProductCombo::query()
            ->withCount('items')
            ->when($this->comboSearch !== '', function ($query) {
                $term = '%'.$this->comboSearch.'%';
                $query->where(function ($inner) use ($term) {
                    $inner->where('name', 'like', $term)
                        ->orWhere('slug', 'like', $term);
                });
            })
            ->orderBy('sort_order')
            ->orderByDesc('id')
            ->paginate($this->perPage, ['*'], 'combosPage');

        $coupons = StorefrontCoupon::query()
            ->when($this->couponSearch !== '', function ($query) {
                $term = '%'.strtoupper($this->couponSearch).'%';
                $query->where(function ($inner) use ($term) {
                    $inner->whereRaw('UPPER(name) like ?', [$term])
                        ->orWhereRaw('UPPER(code) like ?', [$term]);
                });
            })
            ->orderByDesc('id')
            ->paginate($this->perPage, ['*'], 'couponsPage');

        return view('livewire.storefront.admin.product-manager', [
            'products' => $products,
            'combos' => $combos,
            'coupons' => $coupons,
            'categories' => InventoryCategory::query()->orderBy('name')->get(['id', 'name']),
            'productOptions' => InventoryItem::query()
                ->where('status', 'active')
                ->where('is_active', true)
                ->orderBy('name')
                ->get(['id', 'name', 'sku']),
        ]);
    }
}
