<div class="mx-auto max-w-7xl space-y-5">
    <section class="rounded-2xl p-5 text-white shadow-lg sm:p-6" style="background: linear-gradient(135deg, var(--tm-hero) 0%, color-mix(in srgb, var(--tm-hero) 88%, #ffffff 12%) 100%);" data-theme-hero data-orders-workspace-header data-workspace-breadcrumb-accent="secondary">
        <div class="flex items-center justify-between gap-4">
            <div>
                <flux:breadcrumbs class="mb-5 text-white/70">
                    <flux:breadcrumbs.item :href="route('dashboard')" icon="home" class="!text-white/70 hover:!text-white" wire:navigate />
                    <flux:breadcrumbs.item :href="route('orders.index')" class="!text-white/70 hover:!text-white" wire:navigate>{{ __('Orders') }}</flux:breadcrumbs.item>
                    <flux:breadcrumbs.item :href="route('order-catalog.index', ['tab' => 'packages'])" class="!text-white/70 hover:!text-white" wire:navigate>{{ __('Order Catalog') }}</flux:breadcrumbs.item>
                    <flux:breadcrumbs.item class="!text-white">{{ $templateId ? __('Edit Package') : __('New Package') }}</flux:breadcrumbs.item>
                </flux:breadcrumbs>
                <div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-2xl font-semibold">{{ $templateId ? __('Edit Package') : __('New Package') }}</h1>@if ($templateId)<span class="rounded-full bg-white/10 px-2.5 py-1 text-xs text-white/70">{{ $code }} · {{ __('Revision :revision', ['revision' => $revision]) }}</span>@endif</div>
                <p class="mt-1 text-sm text-white/65">{{ __('Build a reusable commercial package from garments, services and branch inventory products.') }}</p>
            </div>
            <a href="{{ route('order-catalog.index', ['tab' => 'packages']) }}" wire:navigate class="rounded-xl p-2 text-white/70 hover:bg-white/10 hover:text-white" aria-label="{{ __('Close') }}"><i class="fa-solid fa-xmark text-xl"></i></a>
        </div>
    </section>

    <form wire:submit="save" class="space-y-5">
        <section class="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#1e1f2e] sm:p-6">
            <div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-lg bg-lime-100 font-bold text-lime-700 dark:bg-lime-400/10">A</span><h2 class="font-semibold text-zinc-900 dark:text-white">{{ __('Package Details') }}</h2></div>
            <div class="mt-5 grid gap-5 md:grid-cols-2">
                <div class="md:col-span-2"><flux:input wire:model="name" label="{{ __('Name') }}" required />@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div class="md:col-span-2"><flux:textarea wire:model="description" label="{{ __('Description') }}" rows="3" /></div>
                <div class="md:col-span-2">
                    <label class="mb-2 block text-sm font-medium text-zinc-700 dark:text-zinc-200">{{ __('Cover image') }}</label>
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-center"><div class="flex h-24 w-36 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-zinc-100 dark:bg-white/5">@if ($coverImageUpload)<img src="{{ $coverImageUpload->temporaryUrl() }}" alt="" class="size-full object-cover">@elseif ($existingCoverImagePath && ! $removeCoverImage)<img src="{{ app(\App\Services\Media\ImageUploadService::class)->publicUrl($existingCoverImagePath) }}" alt="" class="size-full object-cover">@else<i class="fa-duotone fa-image text-2xl text-zinc-400"></i>@endif</div><div class="flex-1"><input type="file" wire:model="coverImageUpload" accept="image/jpeg,image/png,image/webp" class="block w-full rounded-xl border border-zinc-200 p-2 text-sm dark:border-white/10"><p class="mt-1 text-xs text-zinc-500">{{ __('JPG, PNG or WebP, up to 2 MB.') }}</p>@if ($existingCoverImagePath)<label class="mt-2 inline-flex items-center gap-2 text-sm"><input type="checkbox" wire:model="removeCoverImage" class="rounded border-zinc-300">{{ __('Remove current cover') }}</label>@endif @error('coverImageUpload')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
                </div>
                <div class="md:col-span-2 rounded-xl bg-zinc-50 p-4 dark:bg-white/5">
                    @if ($isGlobalAdmin)<label class="flex items-start gap-3"><input type="checkbox" wire:model.live="availableAllBranches" class="mt-1 rounded border-zinc-300"><span><strong class="block text-sm">{{ __('Available at all branches') }}</strong><span class="text-xs text-zinc-500">{{ __('Inventory products cannot be added while this is enabled because inventory is branch-owned.') }}</span></span></label>@else<p class="text-sm text-zinc-500">{{ __('This package is limited to your assigned branch.') }}</p>@endif
                    @if (! $availableAllBranches)<div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach ($branches as $branch)<label class="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white p-3 text-sm dark:border-white/10 dark:bg-[#1e1f2e]"><input type="checkbox" wire:model.live="branchIds" value="{{ $branch->id }}" class="rounded border-zinc-300" @disabled(! $isGlobalAdmin)>{{ $branch->name }}</label>@endforeach</div>@endif
                    @error('branchIds')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
                </div>
            </div>
        </section>

        <section class="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#1e1f2e] sm:p-6">
            <div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-lg bg-lime-100 font-bold text-lime-700 dark:bg-lime-400/10">B</span><div><h2 class="font-semibold text-zinc-900 dark:text-white">{{ __('Package Contents') }}</h2><p class="text-xs text-zinc-500">{{ __('Add components, set commercial quantities and arrange their display order.') }}</p></div></div>

            <div class="mt-5 grid gap-4 lg:grid-cols-2">
                <div class="rounded-xl border border-zinc-200 p-4 dark:border-white/10">
                    <h3 class="text-sm font-semibold"><i class="fa-duotone fa-shirt mr-2 text-lime-600"></i>{{ __('Garments & Services') }}</h3>
                    <flux:input wire:model.live.debounce.300ms="catalogSearch" class="mt-3" icon="magnifying-glass" placeholder="{{ __('Search active catalog items') }}" />
                    <div class="mt-3 max-h-64 space-y-2 overflow-y-auto">@forelse ($catalogItems as $item)<div class="flex items-center gap-3 rounded-xl bg-zinc-50 p-2.5 dark:bg-white/5"><div class="flex size-10 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-white dark:bg-white/10">@if($item->image_url)<img src="{{ $item->image_url }}" alt="" class="size-full object-cover">@else<i class="fa-duotone fa-shirt text-zinc-400"></i>@endif</div><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium">{{ $item->name }}</p><p class="text-xs text-zinc-500">{{ $item->code }} · {{ money_currency($item->default_selling_price) }}</p></div><flux:button type="button" size="sm" wire:click="addCatalogItem({{ $item->id }})" icon="plus" aria-label="{{ __('Add :name', ['name' => $item->name]) }}" /></div>@empty<p class="py-6 text-center text-sm text-zinc-500">{{ __('No active catalog items match this package availability.') }}</p>@endforelse</div>
                </div>
                <div class="rounded-xl border border-zinc-200 p-4 dark:border-white/10">
                    <h3 class="text-sm font-semibold"><i class="fa-duotone fa-box mr-2 text-indigo-500"></i>{{ __('Inventory Products') }}</h3>
                    <p class="mt-1 text-xs text-zinc-500">{{ __('Choose exactly one package branch to select its inventory. No stock is reserved here.') }}</p>
                    <flux:input wire:model.live.debounce.300ms="inventorySearch" class="mt-3" icon="magnifying-glass" placeholder="{{ __('Search name or SKU') }}" :disabled="$availableAllBranches || count($branchIds) !== 1" />
                    <div class="mt-3 max-h-64 space-y-2 overflow-y-auto">@forelse ($inventoryItems as $item)<div class="flex items-center gap-3 rounded-xl bg-zinc-50 p-2.5 dark:bg-white/5"><div class="flex size-10 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-white dark:bg-white/10">@if($item->featured_image_url)<img src="{{ $item->featured_image_url }}" alt="" class="size-full object-cover">@else<i class="fa-duotone fa-box text-zinc-400"></i>@endif</div><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium">{{ $item->name }}</p><p class="text-xs text-zinc-500">{{ $item->sku ?: __('No SKU') }} · {{ money_currency($item->default_sell_price) }} · {{ __('Available: :qty', ['qty' => number_format($item->available_qty, 2)]) }}</p></div><flux:button type="button" size="sm" wire:click="addInventoryItem({{ $item->id }})" icon="plus" aria-label="{{ __('Add :name', ['name' => $item->name]) }}" /></div>@empty<p class="py-6 text-center text-sm text-zinc-500">{{ $availableAllBranches || count($branchIds) !== 1 ? __('Select one branch to browse its inventory products.') : __('No active inventory products match your search.') }}</p>@endforelse</div>
                </div>
            </div>

            <div class="mt-5 space-y-3">
                @forelse ($components as $index => $packageComponent)
                    <article wire:key="package-component-{{ $packageComponent['source_type'] }}-{{ $packageComponent['source_id'] }}-{{ $index }}" class="rounded-xl border border-zinc-200 p-4 dark:border-white/10">
                        <div class="flex flex-col gap-4 xl:flex-row xl:items-start">
                            <div class="flex min-w-0 flex-1 items-center gap-3"><div class="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-zinc-100 dark:bg-white/5">@if($packageComponent['image_url'])<img src="{{ $packageComponent['image_url'] }}" alt="" class="size-full object-cover">@else<i class="fa-duotone {{ $packageComponent['source_type'] === 'catalog_item' ? 'fa-shirt' : 'fa-box' }} text-zinc-400"></i>@endif</div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="truncate text-sm font-semibold">{{ $packageComponent['name'] }}</h3><flux:badge size="sm" color="{{ $packageComponent['source_type'] === 'catalog_item' ? 'lime' : 'indigo' }}">{{ $packageComponent['source_type'] === 'catalog_item' ? __('Garment / Service') : __('Inventory Product') }}</flux:badge>@if($packageComponent['source_archived'])<flux:badge size="sm" color="amber">{{ __('Historical source') }}</flux:badge>@endif</div><p class="text-xs text-zinc-500">{{ $packageComponent['source_code'] ?: __('No code') }} · {{ __('Standard price: :price', ['price' => money_currency($packageComponent['standard_unit_price'])]) }}</p></div></div>
                            <div class="flex items-center gap-1 self-end xl:self-start"><button type="button" wire:click="moveComponent({{ $index }}, 'up')" @disabled($loop->first) class="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 disabled:opacity-30 dark:hover:bg-white/5" aria-label="{{ __('Move up') }}"><i class="fa-solid fa-arrow-up"></i></button><button type="button" wire:click="moveComponent({{ $index }}, 'down')" @disabled($loop->last) class="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 disabled:opacity-30 dark:hover:bg-white/5" aria-label="{{ __('Move down') }}"><i class="fa-solid fa-arrow-down"></i></button><button type="button" wire:click="removeComponent({{ $index }})" class="rounded-lg p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10" aria-label="{{ __('Remove component') }}"><i class="fa-solid fa-trash-can"></i></button></div>
                        </div>
                        @if($packageComponent['source_archived'])<p class="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">{{ __('This historical source is archived or inactive. It remains visible and will not be offered for new additions.') }}</p>@endif
                        <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><flux:input wire:model.live.debounce.200ms="components.{{ $index }}.minimum_quantity" type="number" min="0" step="0.01" label="{{ __('Minimum') }}" /><flux:input wire:model.live.debounce.200ms="components.{{ $index }}.default_quantity" type="number" min="0" step="0.01" label="{{ __('Default') }}" /><flux:input wire:model.live.debounce.200ms="components.{{ $index }}.maximum_quantity" type="number" min="0" step="0.01" label="{{ __('Maximum') }}" placeholder="{{ __('No limit') }}" /><x-money-input wire:model.blur="components.{{ $index }}.package_unit_price" min="0" step="0.01" label="{{ __('Package unit price') }}" /><div class="rounded-xl bg-zinc-50 px-3 py-2 dark:bg-white/5"><span class="block text-xs text-zinc-500">{{ __('Component total') }}</span><strong class="mt-1 block text-sm">{{ money_currency(app(\App\Services\Orders\OrderPackagePricingService::class)->componentPackageTotal((string) $packageComponent['default_quantity'], (string) $packageComponent['package_unit_price'])) }}</strong><span class="text-xs {{ (float) $packageComponent['minimum_quantity'] > 0 ? 'text-indigo-600' : 'text-zinc-500' }}">{{ (float) $packageComponent['minimum_quantity'] > 0 ? __('Required') : __('Optional') }}</span></div></div>
                        @error("components.$index.minimum_quantity")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @error("components.$index.default_quantity")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @error("components.$index.maximum_quantity")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @error("components.$index.package_unit_price")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
                    </article>
                @empty
                    <div class="rounded-xl border border-dashed border-zinc-300 px-5 py-10 text-center dark:border-white/15"><i class="fa-duotone fa-layer-plus text-3xl text-zinc-300"></i><p class="mt-3 text-sm font-medium">{{ __('No components added') }}</p><p class="mt-1 text-xs text-zinc-500">{{ __('Use either source panel above to begin building this package.') }}</p></div>
                @endforelse
                @error('components')<p class="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-500/10 dark:text-red-300">{{ $message }}</p>@enderror
            </div>
        </section>

        <section class="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#1e1f2e]" data-form-actions="package-template">
            <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-lg bg-lime-100 font-bold text-lime-700 dark:bg-lime-400/10">C</span><div><h2 class="text-sm font-semibold">{{ __('Package Pricing') }}</h2><p class="text-xs text-zinc-500">{{ __('Calculated exactly from default quantities and component prices.') }}</p></div></div>
                <div class="grid gap-3 text-left sm:grid-cols-3 sm:gap-4 sm:text-right"><div><span class="block text-xs text-zinc-500">{{ __('Standard Value') }}</span><strong>{{ money_currency($pricingSummary['standard_value']) }}</strong></div><div><span class="block text-xs text-zinc-500">{{ __('Package Price') }}</span><strong>{{ money_currency($pricingSummary['package_price']) }}</strong></div><div><span class="block text-xs text-zinc-500">{{ (float) $pricingSummary['difference'] >= 0 ? __('Customer Saves') : __('Price Difference') }}</span><strong class="{{ (float) $pricingSummary['difference'] >= 0 ? 'text-emerald-600' : 'text-amber-600' }}">{{ money_currency(abs((float) $pricingSummary['difference'])) }}</strong></div></div>
                <div class="grid gap-2 sm:grid-flow-col sm:auto-cols-max sm:justify-end"><flux:button :href="route('order-catalog.index', ['tab' => 'packages'])" wire:navigate variant="ghost" class="w-full sm:w-auto">{{ __('Cancel') }}</flux:button><flux:button type="submit" variant="primary" icon="check" class="w-full sm:w-auto">{{ $templateId ? __('Save Package') : __('Create Package') }}</flux:button></div>
            </div>
        </section>
    </form>
</div>
